### ISSUE TITLE
Text on the download menu is blurred

### ISSUE THREAD

**Issue by Rafii2198** [DrBiznes/WynnLODGrabber#1]
**Describe the bug**
The text on the download menu is blurred by the default minecraft gui blur, and thus is really hard to read.
![image](https://github.com/user-attachments/assets/33c6ba34-8516-4541-befa-8fb988e7ce6f)

**Environment:**
 - OS: Windows
 - Minecraft Version: 1.21.1
 - Mod Version: 1.0.2
 - Other Mods Installed: **Only** latest versions of dependencies, nothing else

**Comment by DrBiznes** [comment]
Oops I have the default blur set to 0% so I didn't catch this I'll fix it and the other bug you reported in the next update

**Comment by Rafii2198** [comment]
I don't usually ask this, but do you have an eta on that? I really would want to include the mod in my modpack, but I am a bit behind with the update, so if it takes you some time I believe I can do some stuff on my end to temporarily fix it

**Comment by DrBiznes** [comment]
I'll try to get it out today I also need to update my modpack for 2.1.1 lol
